spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: bl://gmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: TRACE # 查看底层网络通信
    org.springframework.cloud.loadbalancer: TRACE # 如果使用Spring Cloud LoadBalancer
    # 如果你使用了Resilience4j作为熔断器，也请开启
    io.github.resilience4j: DEBUG
    # 如果你使用了Hystrix作为熔断器（较老版本），也请开启
    com.netflix.hystrix: DEBUG
    com.alibaba.cloud.nacos.discovery: DEBUG # Nacos发现已确认健康，DEBUG就够了
    com.alibaba.nacos: DEBUG # Nacos相关也DEBUG